apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-config
  namespace: tds-group-3
data:
  PORT: "3000"
  DB_PORT: "5432"
  JWT_EXPIRES_IN: "8h"
  APP_URL: "https://tds-group-3.tds-linar.udesa.edu.ar"
  ALLOWED_EMAIL_DOMAIN: "udesa.edu.ar"
  INITIAL_SUPERADMIN_EMAIL: "admin@udesa.edu.ar"
  SMTP_PORT: "587"
  SMTP_FROM: "backoffice@udesa.edu.ar"
  USERS_SERVICE_URL: "http://users:3000"
  FRIENDS_SERVICE_URL: "http://friends:3000"
  LOCATION_SERVICE_URL: "http://location:3000"
  API_GATEWAY_URL: "http://api-gateway:4000"
