apiVersion: v1
kind: Secret
metadata:
  name: backoffice-secret
  namespace: tds-group-3
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ADMIN_JWT_SECRET: "${ADMIN_JWT_SECRET}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_USER: "${SMTP_USER}"
  SMTP_PASS: "${SMTP_PASS}"
  INITIAL_SUPERADMIN_TEMP_PASSWORD: "${INITIAL_SUPERADMIN_TEMP_PASSWORD}"
