apiVersion: v1
kind: Service
metadata:
  name: backoffice
  namespace: group-3
  labels:
    app: backoffice
spec:
  type: ClusterIP
  selector:
    app: backoffice
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
